---  
- name: install/run minecraft server
  hosts: all
  become: true

  tasks: 
    - name: "Updating packages"
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: True    

    - name: Install Java
      apt:
        name: openjdk-8-jdk-headless
        state: present
        

    - name: download minecraft server 1.16.5
      get_url:
        url: https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar
        dest: /root
  
    - name: installing server
      shell: java -Xms1G -Xmx1G -jar server.jar --nogui

    - name: accept eula 
      lineinfile: 
        path: /root/eula.txt
        regexp: "eula=false"
        line: "eula=true"

    - name: copy minecraft.service file in /etc/systemd/system
      copy: 
        src: /root/minecraft/minecraft-server.service
        dest: /etc/systemd/system/minecraft-server.service

    - name: reload systemctl daemon
      systemd:
        daemon_reload: yes

    - name: run the server 
      systemd: name=minecraft-server state=started
      
